### ISSUE TITLE
Zenpower Not Found (Cezanne)

### ISSUE THREAD

**Issue by aviezab** [Ta180m/zenpower3#3] opened 2021-10-22 01:57 UTC
This issue raised during elaboration of searching Cezanne debug data --> https://github.com/Ta180m/zenmonitor3/issues/7
The zenpower3 is flawlessly installed but using this script https://gist.github.com/ocerman/6566b00072c8af96a109f65075f2d8b7 
I didn't get any debug data.

![image](https://user-images.githubusercontent.com/34294278/138380560-c767dbad-dc2f-45a2-88f8-6aaf0e6e4712.png)

dmesg message:
```
sudo dmesg | grep zen
[    0.203531] smpboot: CPU0: AMD Ryzen 5 5600H with Radeon Graphics (family: 0x19, model: 0x50, stepping: 0x0)
[    0.699758] zenpower: loading out-of-tree module taints kernel.
[    0.699774] zenpower: module verification failed: signature and/or required key missing - tainting kernel
```

I am using Arch Linux with latest Kernel
```
uname -a -r
Linux DELLG15-ARCH 5.14.14-AMD #1 SMP PREEMPT Thu Oct 21 18:01:25 WIB 2021 x86_64 GNU/Linux
```

**Comment by Ta180m** [comment] 2021-12-15 15:22
Closing as a duplicate of #2.

**Closed by Ta180m** 2021-12-15 15:22 UTC
Labels: duplicate
